//! The six cases from HANDOVER section 6, driven through the real host.
//!
//! These spawn `aegis-host.exe`, speak the native-messaging protocol to it over
//! a pipe, and place real files in the real quarantine directory — the same
//! path the browser writes to. The only part of the production flow not
//! exercised here is the browser itself deciding to call
//! `onDeterminingFilename`.
//!
//! ## Why this file exists separately from `ipc_roundtrip.rs`
//!
//! That file tests the protocol: malformed frames, paths outside the
//! quarantine root, the retired chunk protocol. This one tests the *verdicts* —
//! whether Aegis reaches the right conclusion about a realistic file, and
//! whether it says something a person could act on.
//!
//! ## Half of these assert that files are RELEASED
//!
//! That is deliberate and it is the half more likely to catch a regression.
//! Every check added to Aegis is a fresh chance to start blocking ordinary
//! downloads, and a scanner that blocks everything is indistinguishable from a
//! broken one — except that the broken one is more honest about it.
//!
//! ## Fixtures
//!
//! Generated by `scripts/make_test_files.py`, not committed: several are
//! deliberately malicious-looking and a repository full of things that trip
//! antivirus scanners is its own problem. Tests skip cleanly when a fixture is
//! absent, because a test that could not run must never be confused with one
//! that passed.
//!
//! There is deliberately no EICAR. On a machine with Defender running it
//! measures Defender, not Aegis.

use std::io::{Read, Write};
use std::path::PathBuf;
use std::process::{Command, Stdio};

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("aegis-host has a parent")
        .to_path_buf()
}

fn downloads_dir() -> PathBuf {
    #[cfg(windows)]
    let home = std::env::var("USERPROFILE").unwrap_or_default();
    #[cfg(not(windows))]
    let home = std::env::var("HOME").unwrap_or_default();
    PathBuf::from(home).join("Downloads")
}

fn frame(value: &serde_json::Value) -> Vec<u8> {
    let json = serde_json::to_vec(value).expect("serialize");
    let mut out = (json.len() as u32).to_le_bytes().to_vec();
    out.extend_from_slice(&json);
    out
}

fn parse_frames(buf: &[u8]) -> Vec<serde_json::Value> {
    let mut out = Vec::new();
    let mut pos = 0usize;
    while pos + 4 <= buf.len() {
        let len =
            u32::from_le_bytes([buf[pos], buf[pos + 1], buf[pos + 2], buf[pos + 3]]) as usize;
        pos += 4;
        if pos + len > buf.len() {
            break;
        }
        if let Ok(v) = serde_json::from_slice(&buf[pos..pos + len]) {
            out.push(v);
        }
        pos += len;
    }
    out
}

/// The outcome of putting one file through Aegis.
struct Outcome {
    status: String,
    verdict: String,
    findings: Vec<serde_json::Value>,
}

impl Outcome {
    /// Everything the user would be shown, flattened for searching.
    fn user_visible_text(&self) -> String {
        let mut s = self.verdict.clone();
        for f in &self.findings {
            for key in ["title", "why", "detail"] {
                if let Some(v) = f.get(key).and_then(|v| v.as_str()) {
                    s.push(' ');
                    s.push_str(v);
                }
            }
        }
        s
    }

    fn severities(&self) -> Vec<String> {
        self.findings
            .iter()
            .filter_map(|f| f.get("severity").and_then(|s| s.as_str()))
            .map(|s| s.to_string())
            .collect()
    }
}

/// Put `fixture` through the host as though the browser had just written it.
///
/// Returns `None` when the fixture or the Downloads directory is missing.
fn scan(fixture: &str, uuid: &str, presented_as: &str) -> Option<Outcome> {
    let source = repo_root().join("test_files").join(fixture);
    let content = std::fs::read(&source).ok()?;

    let downloads = downloads_dir();
    let quarantine = downloads.join("aegis_quarantine");
    std::fs::create_dir_all(&quarantine).ok()?;

    // Mirror what Chromium does: UUID stem, browser-chosen extension.
    let ext = std::path::Path::new(presented_as)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("bin");
    let planted = quarantine.join(format!("{uuid}.{ext}"));
    std::fs::write(&planted, &content).ok()?;

    let input = frame(&serde_json::json!({
        "type": "WATCH_BEGIN",
        "session_id": uuid,
        "quarantine_path": planted.to_string_lossy(),
        "original_filename": presented_as,
    }));

    let mut child = Command::new(env!("CARGO_BIN_EXE_aegis-host"))
        .current_dir(repo_root())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn aegis-host");

    // Every I/O result is collected BEFORE any early return, so the child is
    // always waited on. Bailing out with `?` between spawn and wait would leave
    // a zombie process behind for each skipped fixture.
    let mut stdout = Vec::new();
    let mut stderr = String::new();
    let wrote = child.stdin.take().unwrap().write_all(&input);
    let read = child.stdout.take().unwrap().read_to_end(&mut stdout);
    let _ = child.stderr.take().unwrap().read_to_string(&mut stderr);
    let _ = child.wait();
    wrote.ok()?;
    read.ok()?;

    // Clean up both the quarantine copy and anything released.
    let _ = std::fs::remove_file(&planted);
    let _ = std::fs::remove_file(downloads.join(presented_as));

    assert!(
        !stderr.contains("panicked"),
        "host panicked scanning {fixture}: {stderr}"
    );

    let frames = parse_frames(&stdout);
    // The LAST verdict: an early block sends one mid-transfer and a final one
    // afterwards, and the final one is the outcome.
    let verdict = frames
        .iter()
        .rfind(|f| f.get("type").and_then(|t| t.as_str()) == Some("VERDICT"))?;

    Some(Outcome {
        status: verdict
            .get("status")
            .and_then(|s| s.as_str())
            .unwrap_or("")
            .to_string(),
        verdict: verdict
            .get("verdict")
            .and_then(|s| s.as_str())
            .unwrap_or("")
            .to_string(),
        findings: verdict
            .get("findings")
            .and_then(|f| f.as_array())
            .cloned()
            .unwrap_or_default(),
    })
}

const SKIP: &str = "fixture missing — run scripts/make_test_files.py";

// ---------------------------------------------------------------------------
// Files that must be DELIVERED
// ---------------------------------------------------------------------------

#[test]
fn benign_pdf_is_released() {
    let Some(o) = scan(
        "benign_document.pdf",
        "aaaaaaaa-0000-4000-8000-000000000001",
        "benign_document.pdf",
    ) else {
        eprintln!("{SKIP}");
        return;
    };
    assert_eq!(
        o.status, "COMPLETE",
        "an ordinary PDF must be released: {}",
        o.verdict
    );
}

/// The single most important regression guard in the suite.
///
/// An archive containing source code, documentation and a licence is what most
/// downloaded archives are. If archive inspection ever starts blocking this,
/// it has become a false-positive generator.
#[test]
fn ordinary_source_archive_is_released() {
    let Some(o) = scan(
        "ordinary_project.zip",
        "aaaaaaaa-0000-4000-8000-000000000002",
        "ordinary_project.zip",
    ) else {
        eprintln!("{SKIP}");
        return;
    };
    assert_eq!(
        o.status, "COMPLETE",
        "an ordinary source archive must be released: {}",
        o.verdict
    );
}

/// A binary signed by Microsoft must be released, and the user should be told
/// who signed it.
///
/// Most Windows binaries carry no *embedded* signature — they are covered by a
/// signed system catalogue — so this exercises the catalogue path, which is
/// exactly the one an embedded-only check gets wrong by calling `notepad.exe`
/// unsigned.
#[test]
fn signed_windows_binary_is_released_and_names_its_publisher() {
    let Some(o) = scan(
        "signed_windows_binary.exe",
        "aaaaaaaa-0000-4000-8000-000000000003",
        "signed_windows_binary.exe",
    ) else {
        eprintln!("{SKIP}");
        return;
    };

    assert_eq!(
        o.status, "COMPLETE",
        "a Microsoft-signed Windows binary must be released: {}",
        o.verdict
    );

    let text = o.user_visible_text().to_lowercase();
    assert!(
        text.contains("signed") || text.contains("catalog") || text.contains("catalogue"),
        "provenance was verified but never shown to the user. This is the whole \
         user-visible payoff of Authenticode, and it only ever appears on files \
         that PASS. verdict={:?} findings={:?}",
        o.verdict,
        o.findings
    );
}

// ---------------------------------------------------------------------------
// Files that must NOT be delivered
// ---------------------------------------------------------------------------

/// The case archive inspection was written for.
///
/// Every other check sees an ordinary file: the container is a well-formed ZIP,
/// its entropy is normal for compressed data, and `structure.rs` deliberately
/// does not flag executables inside archives.
#[test]
fn archive_hiding_a_disguised_executable_is_blocked() {
    let Some(o) = scan(
        "invoice_archive.zip",
        "aaaaaaaa-0000-4000-8000-000000000004",
        "invoice_archive.zip",
    ) else {
        eprintln!("{SKIP}");
        return;
    };

    assert_ne!(
        o.status, "COMPLETE",
        "a ZIP containing invoice.pdf.exe must not be delivered: {}",
        o.verdict
    );
    assert!(
        o.user_visible_text().contains("invoice.pdf.exe"),
        "the verdict must name the entry responsible. Telling someone their \
         download was blocked without saying which file caused it leaves them \
         unable to judge whether the block was right. verdict={:?} findings={:?}",
        o.verdict,
        o.findings
    );
}

/// An executable wearing an image extension must not be delivered.
///
/// This is the canonical case and it guards the recalibration that let
/// `notepad.exe` through. String matches were capped well below the block
/// threshold because API names in a *program* mean nothing — but in a file
/// claiming to be a JPEG they are exactly the corroboration that matters, and
/// `deep_forensic_scan` adds them to the magic-byte mismatch for that reason.
///
/// If capping the strings ever silently disarms this, the cap went too far.
#[test]
fn executable_disguised_as_an_image_is_not_delivered() {
    let Some(o) = scan(
        "test_trojan.jpg",
        "aaaaaaaa-0000-4000-8000-000000000007",
        "holiday_photo.jpg",
    ) else {
        eprintln!("{SKIP}");
        return;
    };

    assert_ne!(
        o.status, "COMPLETE",
        "a program named .jpg must never be delivered: {}",
        o.verdict
    );

    let text = o.user_visible_text().to_lowercase();
    assert!(
        text.contains("not the type") || text.contains("claims") || text.contains("exe"),
        "the verdict must say the file is not what its name claims: {:?}",
        o.verdict
    );
}

/// An encrypted archive must be reported as UNSCANNABLE, never as clean.
///
/// Nothing can read inside it — not Aegis, not Defender — which is exactly why
/// malware campaigns ship password-protected archives with the password in the
/// email body. The decryption step moves to a human, past every automated check.
#[test]
fn encrypted_archive_is_reported_as_unscannable() {
    let Some(o) = scan(
        "protected_documents.zip",
        "aaaaaaaa-0000-4000-8000-000000000005",
        "protected_documents.zip",
    ) else {
        eprintln!("{SKIP}");
        return;
    };

    let text = o.user_visible_text().to_lowercase();
    assert!(
        text.contains("password") || text.contains("encrypted"),
        "an encrypted archive must be reported as unreadable rather than \
         silently treated as clean: status={} verdict={:?}",
        o.status,
        o.verdict
    );
}

/// A macro stream inside a format that cannot legitimately have one.
///
/// `.docx` is macro-free by definition, so `vbaProject.bin` inside one is a
/// mismatch nobody creates by accident. The same stream inside a `.docm` is
/// reported and not condemned — the user asked for a macro-enabled document.
#[test]
fn macro_in_a_macro_free_format_is_flagged() {
    let Some(o) = scan(
        "quarterly_report.docx",
        "aaaaaaaa-0000-4000-8000-000000000006",
        "quarterly_report.docx",
    ) else {
        eprintln!("{SKIP}");
        return;
    };

    let text = o.user_visible_text().to_lowercase();
    assert!(
        text.contains("macro"),
        "a macro inside a .docx must be reported: status={} verdict={:?} findings={:?}",
        o.status,
        o.verdict,
        o.findings
    );
    assert_ne!(
        o.status, "COMPLETE",
        "a macro in a macro-free format is a deliberate mismatch and must not \
         be delivered: {}",
        o.verdict
    );
}

// ---------------------------------------------------------------------------
// Explanation quality
// ---------------------------------------------------------------------------

/// A blocked file must arrive with an explanation a person can act on.
///
/// The verdict string alone is not enough. `finding.rs` exists because
/// `[risk=0.60] CreateRemoteThread (utf-8)` is accurate and useless to the
/// person whose download just vanished: it names an API without saying what the
/// file was trying to do or why they should care.
#[test]
fn blocked_files_carry_an_explanation_not_just_a_score() {
    for (fixture, uuid) in [
        ("invoice_archive.zip", "aaaaaaaa-0000-4000-8000-00000000000a"),
        ("quarterly_report.docx", "aaaaaaaa-0000-4000-8000-00000000000b"),
    ] {
        let Some(o) = scan(fixture, uuid, fixture) else {
            eprintln!("{SKIP}");
            return;
        };
        if o.status == "COMPLETE" {
            continue;
        }

        assert!(
            !o.findings.is_empty(),
            "{fixture} was blocked with no structured findings — the user gets a \
             refusal and no reason"
        );

        for f in &o.findings {
            for key in ["title", "why"] {
                let v = f.get(key).and_then(|v| v.as_str()).unwrap_or("");
                assert!(
                    !v.trim().is_empty(),
                    "{fixture}: a finding has an empty {key:?}, so part of the \
                     explanation renders blank: {f:?}"
                );
            }
        }

        assert!(
            !o.severities().is_empty(),
            "{fixture}: findings carry no severity, so the popup cannot order \
             them and a notification cannot pick the one that matters"
        );
    }
}

/// Nothing is ever left behind in quarantine.
///
/// A blocked file that stays on disk is a malicious file sitting in a
/// subdirectory of the user's Downloads folder, which is most of what Aegis
/// exists to prevent.
#[test]
fn quarantine_is_left_empty_whatever_the_verdict() {
    let downloads = downloads_dir();
    let quarantine = downloads.join("aegis_quarantine");
    if std::fs::create_dir_all(&quarantine).is_err() {
        return;
    }

    for (fixture, uuid) in [
        ("benign_document.pdf", "aaaaaaaa-0000-4000-8000-00000000000c"),
        ("invoice_archive.zip", "aaaaaaaa-0000-4000-8000-00000000000d"),
        ("protected_documents.zip", "aaaaaaaa-0000-4000-8000-00000000000e"),
    ] {
        if scan(fixture, uuid, fixture).is_none() {
            eprintln!("{SKIP}");
            return;
        }
        let leftover: Vec<_> = std::fs::read_dir(&quarantine)
            .into_iter()
            .flatten()
            .flatten()
            .filter(|e| e.file_name().to_string_lossy().starts_with(uuid))
            .collect();
        assert!(
            leftover.is_empty(),
            "{fixture} left {} file(s) in quarantine after the verdict",
            leftover.len()
        );
    }
}
